#ifndef DAVINCIDEVSYS_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define DAVINCIDEVSYS_MAJOR_VERSION 38
#define DAVINCIDEVSYS_MINOR_VERSION 1
#define DAVINCIDEVSYS_PATCH_VERSION 1
#define DAVINCIDEVSYS_VERSION CALC_GAUDI_VERSION(DAVINCIDEVSYS_MAJOR_VERSION,DAVINCIDEVSYS_MINOR_VERSION)
#endif
