#ifndef URANIADEVSYS_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define URANIADEVSYS_MAJOR_VERSION 6
#define URANIADEVSYS_MINOR_VERSION 2
#define URANIADEVSYS_PATCH_VERSION 1
#define URANIADEVSYS_VERSION CALC_GAUDI_VERSION(URANIADEVSYS_MAJOR_VERSION,URANIADEVSYS_MINOR_VERSION)
#endif
