#ifndef DAVINCIDEV_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define DAVINCIDEV_MAJOR_VERSION 38
#define DAVINCIDEV_MINOR_VERSION 1
#define DAVINCIDEV_PATCH_VERSION 1
#define DAVINCIDEV_VERSION CALC_GAUDI_VERSION(DAVINCIDEV_MAJOR_VERSION,DAVINCIDEV_MINOR_VERSION)
#endif
