#ifndef STRIPPINGARCHIVE_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define STRIPPINGARCHIVE_MAJOR_VERSION 1
#define STRIPPINGARCHIVE_MINOR_VERSION 35
#define STRIPPINGARCHIVE_PATCH_VERSION 1
#define STRIPPINGARCHIVE_VERSION CALC_GAUDI_VERSION(STRIPPINGARCHIVE_MAJOR_VERSION,STRIPPINGARCHIVE_MINOR_VERSION)
#endif
