#ifndef PIDPERFTOOLS_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define PIDPERFTOOLS_MAJOR_VERSION 8
#define PIDPERFTOOLS_MINOR_VERSION 2
#define PIDPERFTOOLS_PATCH_VERSION 0
#define PIDPERFTOOLS_VERSION CALC_GAUDI_VERSION(PIDPERFTOOLS_MAJOR_VERSION,PIDPERFTOOLS_MINOR_VERSION)
#endif
