#ifndef COMMONPARTICLES_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define COMMONPARTICLES_MAJOR_VERSION 8
#define COMMONPARTICLES_MINOR_VERSION 23
#define COMMONPARTICLES_PATCH_VERSION 0
#define COMMONPARTICLES_VERSION CALC_GAUDI_VERSION(COMMONPARTICLES_MAJOR_VERSION,COMMONPARTICLES_MINOR_VERSION)
#endif
