#ifndef PIDPERFSCRIPTS_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define PIDPERFSCRIPTS_MAJOR_VERSION 11
#define PIDPERFSCRIPTS_MINOR_VERSION 2
#define PIDPERFSCRIPTS_PATCH_VERSION 0
#define PIDPERFSCRIPTS_VERSION CALC_GAUDI_VERSION(PIDPERFSCRIPTS_MAJOR_VERSION,PIDPERFSCRIPTS_MINOR_VERSION)
#endif
