#ifndef DECAYTREETUPLE_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define DECAYTREETUPLE_MAJOR_VERSION 5
#define DECAYTREETUPLE_MINOR_VERSION 4
#define DECAYTREETUPLE_PATCH_VERSION 0
#define DECAYTREETUPLE_VERSION CALC_GAUDI_VERSION(DECAYTREETUPLE_MAJOR_VERSION,DECAYTREETUPLE_MINOR_VERSION)
#endif
